/* Generated by wayland-scanner 1.26.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface zwlr_virtual_pointer_v1_interface;

static const struct wl_interface *wlr_virtual_pointer_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_seat_interface,
	&zwlr_virtual_pointer_v1_interface,
};

static const struct wl_message zwlr_virtual_pointer_v1_requests[] = {
	{ "motion", "uff", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "motion_absolute", "uuuuu", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "button", "uuu", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "axis", "uuf", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "frame", "", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "axis_source", "u", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "axis_stop", "uu", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "axis_discrete", "uufi", wlr_virtual_pointer_unstable_v1_types + 0 },
	{ "destroy", "", wlr_virtual_pointer_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_virtual_pointer_v1_interface = {
	"zwlr_virtual_pointer_v1", 2,
	9, zwlr_virtual_pointer_v1_requests,
	0, NULL,
};

static const struct wl_message zwlr_virtual_pointer_manager_v1_requests[] = {
	{ "create_virtual_pointer", "?on", wlr_virtual_pointer_unstable_v1_types + 5 },
	{ "destroy", "", wlr_virtual_pointer_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_virtual_pointer_manager_v1_interface = {
	"zwlr_virtual_pointer_manager_v1", 2,
	2, zwlr_virtual_pointer_manager_v1_requests,
	0, NULL,
};

